openapi: 3.0.3
info:
  title: Cosmos DB Demo API
  version: 1.0.0
  description: |
    Simple API for demo Cosmos DB access. Returns a demo item and health status.
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Get demo item from Cosmos DB
      operationId: getDemoItem
      responses:
        '200':
          description: Demo item found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
                  partitionKey:
                    type: string
        '404':
          description: Item not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Database error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: string
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Service healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  database:
                    type: string
                  timestamp:
                    type: string
        '503':
          description: Service unhealthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  database:
                    type: string
                  error:
                    type: string
                  timestamp:
                    type: string
