"""Conversation agent runtime constants."""

CONVERSATION_AGENT_MODE_KNOWLEDGEBASE = "knowledgebase"
CONVERSATION_AGENT_MODE_LLM = "llm"
SUPPORTED_CONVERSATION_AGENT_MODES = {
    CONVERSATION_AGENT_MODE_KNOWLEDGEBASE,
    CONVERSATION_AGENT_MODE_LLM,
}
DEFAULT_CONVERSATION_AGENT_MODE = CONVERSATION_AGENT_MODE_KNOWLEDGEBASE

SUPPORTED_KB_REQUEST_MODES = {"messages", "intents"}
SUPPORTED_KB_OUTPUT_MODES = {"answerSynthesis", "extractiveData"}
SUPPORTED_KB_REASONING_EFFORTS = {"minimal", "low", "medium"}

# Defaults used when client_settings config omits optional fields.
DEFAULT_KB_API_VERSION = "2025-11-01-preview"
DEFAULT_KB_MAX_OUTPUT_SIZE = 5001
MIN_KB_MAX_OUTPUT_SIZE = 500
DEFAULT_KB_MAX_RUNTIME_SECONDS = 30
DEFAULT_KB_MAX_HISTORY_MESSAGES = 10
DEFAULT_KB_REQUEST_MODE = "messages"
DEFAULT_KB_OUTPUT_MODE = "answerSynthesis"
DEFAULT_KB_REASONING_EFFORT = "low"
DEFAULT_AGENT_MAX_TOKENS = 800
DEFAULT_AGENT_TEMPERATURE = 0.1