name: Deploy ACA to Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  builds:
    concurrency:
      group: builds-aca-test-${{ github.run_id }}
      cancel-in-progress: true
    uses: ./.github/workflows/.builds.yml
    with:
      tags: |
        latest
        test-aca-${{ github.run_number }}

  lint:
    uses: ./.github/workflows/.lint.yml

  deploy-aca-test:
    name: Deploy Azure Container Apps to Test
    needs: [builds, lint]
    if: github.event_name == 'workflow_dispatch'
    concurrency:
      group: deploy-aca-test-${{ github.run_id }}
      cancel-in-progress: false
    uses: ./.github/workflows/.deployer_aca.yml
    with:
      command: apply
      tag: test-aca-${{ github.run_number }}
      app_env: test
      environment_name: test
      deployment_type: container_apps
    secrets: inherit
